diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.fsmonitor=true
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\raffa\AppData\Local\Programs\Code\bin\code" --wait
safe.directory=D:/xampp/htdocs/learn
user.email=raffaelaldrichsetiawan@gmail.com
user.name=RaffaelAldrichS
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/RaffaelAldrichS/gadgetku-final-project.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
